typography_spectrum: 0.29634
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.46298992773517966
  lightness: 0.1172486268915236
  saturation: 0.6115805476438254
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.53394
analytics:
  google: null
  facebook: null
  twitter: null
name: Satya Jones
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: BY NOW AT THE SEAWEED HOTEL
description: by
purpose: []
