name: Satya Jones
favicon: null
layout_spectrum: 0.53394
typography_spectrum: 0.1575246239081025
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.46298992773517966
  lightness: 0.1172486268915236
  saturation: 0.6115805476438254
  rhythmicContrast: 0.2927044949028641
purpose: []
